//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOO_Knizhnii_Klub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.ProductsInOrder = new HashSet<ProductsInOrder>();
        }
    
        public int ID { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int OrderStatusID { get; set; }
        public int PickUpPointID { get; set; }
        public int PickUpCode { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual PickUpPoint PickUpPoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsInOrder> ProductsInOrder { get; set; }
    }
}
