//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOO_Knizhnii_Klub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductsInOrder = new HashSet<ProductsInOrder>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ManufacturerID { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> Discount { get; set; }
        public int ProductQuantity { get; set; }
        public string AuthorProduct { get; set; }
        public byte[] Image { get; set; }

        public string ImgPath { 
        
            get { 
                
                return "/Resources/" + this.Name + ".jpg";
                
            }
        }

      
        public string FullViewPrice
        {
            get
            {
                return "Cтоимость: " + Convert.ToString(this.Price) + " Руб";
            }
        }

        public string FullViewQuantity
        {
            get
            {
                return "Осталось: " + this.ProductQuantity;
            }
        }
        public string FullDiscountView
        {
            get
            {
                if (this.Discount == null)
                {
                    return string.Empty;
                }
                else
                {
                    return "Скидка составила: " + Convert.ToString(this.Discount) + " %";
                }
            }
        }

        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsInOrder> ProductsInOrder { get; set; }
    }
}
